version: '3.7'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    ports:
      - 8000:5000
    volumes:
      - .:/source:cached
    env_file: .env
    depends_on:
      - db
  debugger:
    image: debugger
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debugger
    ports:
      - 8000:5000
      - 5678:5678
    volumes:
      - .:/source:cached
    env_file: .env
  test-runner:
    image: test-runner
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    env_file: .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postalgic
    volumes:
      - pgdata:/var/lib/postgresql/data/

  # redis:
  #   image: redis:latest

volumes:
  pgdata: